"""add shared spaces and space_id to records

Revision ID: 73f3d02b401d
Revises: c5fa012b0e45
Create Date: 2026-04-28 17:29:28.451177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f3d02b401d'
down_revision: Union[str, None] = 'c5fa012b0e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('space_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_records_space_id'), 'records', ['space_id'], unique=False)
    op.create_foreign_key(None, 'records', 'shared_spaces', ['space_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_index(op.f('ix_records_space_id'), table_name='records')
    op.drop_column('records', 'space_id')
    # ### end Alembic commands ###
