"""add_category_unique_constraint

Revision ID: c5fa012b0e45
Revises: e12a778ea0f2
Create Date: 2026-04-28 00:36:44.201905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fa012b0e45'
down_revision: Union[str, None] = 'e12a778ea0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_user_name', 'categories', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_user_name', 'categories', type_='unique')
    # ### end Alembic commands ###
